name: Kernel CI (SM-A310F)

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-18.04

    steps:
    - name: Checkout Kernel Source
      uses: actions/checkout@v2

    - name: Getting Toolchain
      run: |
        sudo apt-get install lib32z1 ccache
        sudo git clone --depth 1 --branch android-13.0.0_r0.52 --single-branch https://android.googlesource.com/platform/prebuilts/gcc/linux-x86/aarch64/aarch64-linux-android-4.9 /opt/toolchains/aarch64-linux-android-4.9/
    - name: Building Kernel
      run: |
        export KBUILD_BUILD_USER=notnoelchannel
        export KBUILD_BUILD_HOST=unlegacy-devices
        make -j22 ARCH=arm64 lineageos_a3xelte_defconfig
        make -j128
    - name: Moving Output # CI only
      run: |
        mkdir -p /home/runner/work/output
        cp arch/arm64/boot/Image /home/runner/work/output/zImage
    - name: Uploading Output
      uses: actions/upload-artifact@v2
      with:
        name: zImage
        path: /home/runner/work/output/zImage
